name = "arove"
main = "src/index.ts"
compatibility_date = "2026-04-08"

[[d1_databases]]
binding = "DB"
database_name = "arove-db"
database_id = "11ed36bd-93ff-46ee-993f-84ada2f9ba07"

[[kv_namespaces]]
binding = "CACHE"
id = "e85d4f28e29c4c79b6882fdb162df091"

[triggers]
crons = ["*/1 * * * *"]

[vars]
POLL_INTERVAL_ACTIVE_MS = "60000"
POLL_INTERVAL_IDLE_MS = "300000"
SOCKET_CHECK_INTERVAL_MS = "8000"
RATE_LIMIT_ANONYMOUS_PER_MINUTE = "60"
RATE_LIMIT_AUTHENTICATED_PER_MINUTE = "300"
TOKEN_COUNT = "3"
